# Generated by Django 2.2.19 on 2021-04-04 12:06

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210325_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=product.models.product_thumbnail),
        ),
    ]
